version: "3.9"
    
services:
  db:
    image: mysql:8.0
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    
    restart: always
    ports:
      - "8002:80"

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA:
        define( 'WP_DEBUG_LOG', true );
        define( 'FS_METHOD', 'direct');
        define( 'WP_DEBUG_DISPLAY', 0);
      PHP_ENABLE_OPCACHE: 0

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      UPLOAD_LIMIT: 64M

volumes:
  db_data: {}